apiVersion: apps/v1
kind: Deployment
metadata:
  name: house-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: house
  template:
    metadata:
      labels:
        app: house
    spec:
      containers:
      - name: house-container
        image: juanvieira/house:latest
        ports:
        - containerPort: 5001
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
