apiVersion: v1
kind: Service
metadata:
  name: house-service
spec:
  type: NodePort
  selector:
    app: house
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 30001
