channels:
- conda-forge
dependencies:
- python=3.11.2
- pip<=23.0.1
- pip:
  - mlflow==2.16.0
  - numpy==2.1.1
  - pandas==2.2.2
  - psutil==6.0.0
  - scikit-learn==1.5.2
  - scipy==1.14.1
  - xgboost==2.1.1
name: mlflow-env
